# Set update schedule for GitHub Actions
# This opens a PR when actions in workflows need an update

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "skip changelog" # So this PR will not be added to release-drafter
      include: "scope" # List of the updated dependencies in the commit will be added
