coverage:
  precision: 2
  round: down
  range: 70...98

  ignore:
    - sparse/tests/
    - sparse/_version.py
    - ^(?!sparse\/)

flags:
  project:
    enabled: yes
    target: -3

  patch:
    default:
      enabled: no
