comment:
  layout: "header, diff, changes, uncovered"

coverage:
  status:
    project:
      default:
          # Total project must not drop by more than 3%
          target: auto
          threshold: "3%"
    
    patch:
      enabled: yes
      default:
          # Patch coverage must be 92%
          target: auto
          threshold: "92%"
  
  precision: 2
  round: down
  range: 70...98

  ignore:
    - sparse/tests/
    - sparse/_version.py
    - ^(?!sparse\/)
