comment: false
coverage:
  status:
    project:
      default:
          # Total project must be 95%
          target: '100%'
          threshold: '5%'

    patch:
      default:
          # Patch coverage must be 92%
          target: '100%'
          threshold: '8%'

  precision: 2
  round: down
  range: 80...98
