coverage:
  precision: 2
  round: down
  range: 70...98

  ignore:
    - sparse/tests/
    - sparse/_version.py
    - ^(?!sparse\/)

flags:
  project:
    enabled: yes
    target: auto
    threshold: 1
    if_no_uploads: error
    if_not_found: success
    if_ci_failed: error

  patch:
    default:
      enabled: yes
      target: 95%
      if_no_uploads: error
      if_not_found: success
      if_ci_failed: error
