# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.14.1.dev6+gfb4da47.d20230701'
__version_tuple__ = version_tuple = (0, 14, 1, 'dev6', 'gfb4da47.d20230701')
