name: Bug report
description: Report to help us reproduce the bug
title: "Bug: "
labels: ["bug", "needs triage"]

body:
- type: markdown
  attributes:
    value: >
        ## Thanks for taking the time to fill out this report
- type: checkboxes
  id: checks
  attributes:
    label: sparse version checks
    options:
      - label: >
           I checked that this issue has not been reported before
           [list of issues](https://github.com/pydata/sparse/issues).
        required: true
      - label: >
          I have confirmed this bug exists on the latest version of sparse.
        required: true
      - label: >
            I have confirmed this bug exists on the main branch of sparse.
- type: textarea
  attributes:
    label: Describe the bug
    description: >
       A clear and concise description of what the bug is.
  validations:
       required: true
- type: textarea
  attributes:
    label: Steps or code to reproduce the bug
    description: |
       Please add a minimal code example to reproduce the bug.
  validations:
       required: true
- type: textarea
  attributes:
    label: Expected results
    description: >
       Please paste or describe the expected results.
    placeholder: >
        Example: No error is thrown.
  validations:
        required: true
- type: textarea
  attributes:
    label: Actual results
    description: |
      Please paste or describe the results you observe instead of the expected results.
  validations:
    required: true
- type: textarea
  attributes:
    label: Please describe your system.
    value: |
      1. OS and version: [e.g. Windows 10]
      2. sparse version (sparse.__version__)
      3. NumPy version (np.__version__)
      4. Numba version (numba.__version__)
  validations:
    required: true
- type: textarea
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
