name: Documentation improvement
description: Report to improve the docs. You could also directly open a PR with your suggestions.
title: "Doc: "
labels: ["docs", "needs triage"]

body:
- type: markdown
  attributes:
    value: >
         ## Thanks for taking the time to fill out this form
- type: dropdown
  id: TYPE
  attributes:
    label: What type of report is this?
    options:
      - 'Correction'
      - 'Improvement'
  validations:
      required: true
- type: textarea
  attributes:
    label: Please describe the issue.
    description: >
      Tell us if something is unclear or incorrect, and where.
  validations:
      required: true
- type: textarea
  attributes:
    label: If you have a suggestion on how it should be, add it below.
    description: >
      How can we improve it
- type: markdown
  attributes:
    value: >
        ### If you are interested in opening a pull request to fix this, please let us know.
